name: chat
services:
  app:
    build: .
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - TZ=Asia/Shanghai
      - ETCD_ADDR=etcd:2379
      - NATS_ADDR=nats:4222
    depends_on:
      - nats
      - etcd

  nats:
    image: nats:2.10.25
    environment:
      - TZ=Asia/Shanghai

  etcd:
    image: rancher/hardened-etcd:v3.6.7-k3s1-build20260512
    command:
      - /usr/local/bin/etcd
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://etcd:2379
    environment:
      - TZ=Asia/Shanghai
